image: tsengcy/laravel

stages:
  - install
  - test
  - build
  - deploy
  - migrate

install:php:
  stage: install
  tags:
    - builder
  script:
    - composer config --auth gitlab-token.gitlab.cs.nctu.edu.tw $GITLAB_TOKEN
    - composer install --no-progress
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - vendor

install:js:
  stage: install
  tags:
    - builder
  script:
    - npm install
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - node_modules

test:php:
  stage: test
  tags:
    - builder
  script: 
    - vendor/bin/phpcs --standard=PSR2 app config routes
  dependencies:
    - install:php

test:js:
  stage: test
  tags:
    - builder
  script: 
    - node_modules/eslint/bin/eslint.js resources/assets/js/**/*.{js,vue}
  dependencies:
    - install:js

build:
  stage: build
  tags:
    - builder
  script:
    - sed -i -e "s,^\x24APP_URL:.*,\x24APP_URL:'$APP_URL';,g" resources/assets/sass/_variables.scss
    - sed -i -e "s,^const BASE_PATH = .*,const BASE_PATH = '$BASE_PATH';,g" resources/assets/js/base_path.js
    - npm run production
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - public
  dependencies:
    - install:js

deploy:
  only:
    - dev
  stage: deploy
  tags:
    - training
  script:
    - ssh tccws1 "
        cd /srv/www-available/;
        git clone $CI_REPOSITORY_URL -b $CI_COMMIT_REF_NAME $CI_PROJECT_NAME || 
        ( cd $CI_PROJECT_NAME;
          git remote set-url origin $CI_REPOSITORY_URL;
          git fetch --all;
          git reset --hard origin/$CI_COMMIT_REF_NAME;
        )"
    - scp -r vendor tccws1:/srv/www-available/$CI_PROJECT_NAME/
    - scp -r public tccws1:/srv/www-available/$CI_PROJECT_NAME/
    - ssh tccws1 "
        cd /srv/www-available/$CI_PROJECT_NAME/;
        chmod 775 storage/logs;
        chmod 775 storage/app;
        chmod 775 storage/app/public;
        chmod 775 storage/framework;
        chmod 775 storage/framework/views;
        chmod 775 storage/framework/testing;
        chmod 775 storage/framework/cache;
        chmod 775 storage/framework/sessions;"
  dependencies:
    - install:php
    - build

migrate:
  only:
    - dev
  stage: migrate
  tags:
    - training
  script:
    # Set Env file
    - cp .env.example .env
    - sed -i -e "s,^APP_ENV=.*,APP_ENV=$APP_ENV,g" .env
    - sed -i -e "s,^APP_URL=.*,APP_URL=$APP_URL,g" .env
    - sed -i -e "s,^APP_KEY=.*,APP_KEY=$APP_KEY,g" .env
    - sed -i -e "s,^APP_DEBUG=.*,APP_DEBUG=$APP_DEBUG,g" .env

    - sed -i -e "s,^CSSSO_CLIENT_ID=.*,CSSSO_CLIENT_ID=$CSSSO_CLIENT_ID,g" .env
    - sed -i -e "s,^CSSSO_CLIENT_SECRET=.*,CSSSO_CLIENT_SECRET=$CSSSO_CLIENT_SECRET,g" .env
    - sed -i -e "s,^CSSSO_SERVER=.*,CSSSO_SERVER=$CSSSO_SERVER,g" .env

    - sed -i -e "s,^DB_HOST=.*,DB_HOST=$DB_HOST,g" .env
    - sed -i -e "s,^DB_DATABASE=.*,DB_DATABASE=$DB_DATABASE,g" .env
    - sed -i -e "s,^DB_USERNAME=.*,DB_USERNAME=$DB_USERNAME,g" .env
    - sed -i -e "s,^DB_PASSWORD=.*,DB_PASSWORD=$DB_PASSWORD,g" .env

    - sed -i -e "s,^REDIS_HOST=.*,REDIS_HOST=$REDIS_HOST,g" .env
    - sed -i -e "s,^REDIS_PASSWORD=.*,REDIS_PASSWORD=$REDIS_PASSWORD,g" .env
    - sed -i -e "s,^REDIS_PORT=.*,REDIS_PORT=$REDIS_PORT,g" .env

    - sed -i -e "/LOGGING_STORAGE=.*/d" .env
    - scp .env tccws1:/srv/www-available/$CI_PROJECT_NAME/
    - ssh tccws1 "
          cd /srv/www-available/$CI_PROJECT_NAME/;
          php artisan migrate --force;
          ln -sfn /srv/www-available/$CI_PROJECT_NAME/public/ /srv/www-enable/$CI_PROJECT_NAME;"
  dependencies: []
